package com.botts.impl.sensor.kromek.d5.enums;

public enum KromekSerialRemoteModeState {
    KROMEK_SERIAL_REMOTE_CONTROL_STATE_COMPLETE,
    KROMEK_SERIAL_REMOTE_CONTROL_STATE_CONFIRMATION_IN_PROGRESS,
    KROMEK_SERIAL_REMOTE_CONTROL_STATE_BACKGROUND_IN_PROGRESS,
    KROMEK_SERIAL_REMOTE_CONTROL_STATE_ERROR,
    KROMEK_SERIAL_REMOTE_CONTROL_STATE_INVALID_COMMAND,
    KROMEK_SERIAL_REMOTE_CONTROL_STATE_D5_NOT_READY,
    KROMEK_SERIAL_REMOTE_CONTROL_STATE_INITIALISING;
}
