package com.botts.impl.sensor.kromek.d5.enums;

public enum KromekSerialRemoteControlMode {
    KROMEK_SERIAL_REMOTE_CONTROL_MODE_RESERVED,
    KROMEK_SERIAL_REMOTE_CONTROL_MODE_30,
    KROMEK_SERIAL_REMOTE_CONTROL_MODE_120,
    KROMEK_SERIAL_REMOTE_CONTROL_MODE_300,
    KROMEK_SERIAL_REMOTE_CONTROL_MODE_VARIABLE;
}