package com.botts.impl.sensor.kromek.d5.enums;

public enum KromekSerialPowerSource {
    KROMEK_POWER_SOURCE_UNKNOWN,
    KROMEK_POWER_SOURCE_BATTERY,
    KROMEK_POWER_SOURCE_USB,
    KROMEK_POWER_SOURCE_QI,
    KROMEK_POWER_SOURCE_ETHERNET,
    KROMEK_POWER_SOURCE_BATTERY_BACKUP_AA;
}