package com.botts.impl.sensor.kromek.d5.enums;

public enum KromekSerialRadiationThresholdType {
    KROMEK_UI_CONFIG_RADIATIONTHRESHOLDTYPE_DOSERATE,
    KROMEK_UI_CONFIG_RADIATIONTHRESHOLDTYPE_ACCUMULATEDDOSE,
    KROMEK_UI_CONFIG_RADIATIONTHRESHOLDTYPE_KSIGMAGAMMA,
    KROMEK_UI_CONFIG_RADIATIONTHRESHOLDTYPE_KSIGMANEUTRON,
    KROMEK_UI_CONFIG_RADIATIONTHRESHOLDTYPE_OVERRANGE
}
